DROP TABLE IF EXISTS fact_table;
DROP TABLE IF EXISTS d_tempo;
DROP TABLE IF EXISTS d_meio;
DROP TABLE IF EXISTS d_evento;

-- CRIACAO DAS TABELAS

CREATE TABLE d_evento(
	idEvento INT NOT NULL AUTO_INCREMENT,
	numTelefone INT NOT NULL,
	instanteChamada date,
	PRIMARY KEY (idEvento) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE d_meio(
	idMeio INT NOT NULL AUTO_INCREMENT,
	numMeio INT NOT NULL,
	nomeMeio VARCHAR(15) NOT NULL,
	nomeEntidade VARCHAR(25) NOT NULL,
	tipo VARCHAR (15) NOT NULL,
	PRIMARY KEY (idMeio) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE d_tempo(
	idData int NOT NULL AUTO_INCREMENT,
	dia int NOT NULL,
	mes int NOT NULL,
	ano int NOT NULL,
	PRIMARY KEY (idData) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE fact_table(
	idFact INT NOT NULL AUTO_INCREMENT,
	idEvento INT NOT NULL,
	idMeio INT NOT NULL,
	idData INT NOT NULL,
	PRIMARY KEY (idFact),
	FOREIGN KEY (idEvento) REFERENCES d_evento(idEvento),
	FOREIGN KEY (idMeio) REFERENCES d_meio(idMeio),
	FOREIGN KEY (idData) REFERENCES d_tempo(idData) ON DELETE CASCADE ON UPDATE CASCADE);


-- 
